// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplatefront = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/front/test": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FrontTest"
                ],
                "summary": "前台测试接口",
                "responses": {
                    "200": {
                        "description": "返回 pong",
                        "schema": {
                            "$ref": "#/definitions/response.TestResponseEnvelope"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "response.TestResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "response.TestResponseEnvelope": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/response.TestResponse"
                },
                "msg": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "x-token",
            "in": "header"
        }
    }
}`

// SwaggerInfofront holds exported Swagger Info so clients can modify it
var SwaggerInfofront = &swag.Spec{
	Version:          "v2.9.2",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Gin-Vue-Admin Swagger API接口文档",
	Description:      "使用gin+vue进行极速开发的全栈开发基础平台",
	InfoInstanceName: "front",
	SwaggerTemplate:  docTemplatefront,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfofront.InstanceName(), SwaggerInfofront)
}
