const fs = require("fs");
const path = require("path");

const pages = {
  home: ["pages/home/index"],
  dishForm: ["pages/dish/add-entry", "pages/dish/edit"],
  dishDetail: ["pages/dish/detail"],
  recommend: ["pages/recommend/dishes", "pages/recommend/dish-detail"],
  whatToEat: ["pages/ideas/what-to-eat", "pages/ideas/what-to-eat-detail"],
  recipes: ["pages/recipes/index", "pages/recipes/detail"],
  profile: ["pages/profile/index"],
  checkin: ["pages/checkin/index"],
  meal: ["pages/meal/create", "pages/meal/invite", "pages/meal/vote", "pages/meal/stats"],
  shopping: ["pages/shopping/list"],
  shoppingShare: ["pages/shopping/share"],
  prep: ["pages/meal/prep-guide"],
  points: ["pages/points/index"],
  notifications: ["pages/notifications/index"],
};

function endpoint({
  id,
  module,
  name,
  method,
  path: apiPath,
  usedBy,
  request = {},
  response = {},
  rules = [],
  pagination = false,
  auth = true,
  idempotent = false,
}) {
  return {
    id,
    module,
    name,
    method,
    path: apiPath,
    auth,
    usedBy,
    request,
    response,
    ...(pagination ? { pagination: { request: ["page", "pageSize"], response: ["page", "pageSize", "total", "list"], defaultPageSize: 20 } } : {}),
    ...(idempotent ? { idempotency: { header: "X-Idempotency-Key", required: true } } : {}),
    rules,
  };
}

const interfaces = [
  endpoint({
    id: "bootstrap_get",
    module: "system",
    name: "小程序启动聚合数据",
    method: "GET",
    path: "/bootstrap",
    usedBy: [...pages.home, ...pages.profile],
    response: { $ref: "BootstrapData" },
    rules: ["仅返回首屏所需的小集合；我的菜品最多 3 条，推荐菜品最多 5 条。", "必须返回与登录响应同版本的 RuntimeConfig。"],
  }),
  endpoint({
    id: "auth_wx_login",
    module: "auth",
    name: "微信登录",
    method: "POST",
    path: "/auth/wx-login",
    auth: false,
    usedBy: ["app.js"],
    request: { body: { code: "string|required" } },
    response: { accessToken: "string", expiresIn: "number", isNewUser: "boolean", profile: { $ref: "Profile" }, runtimeConfig: { $ref: "RuntimeConfig" } },
    rules: [
      "App.onLaunch 自动调用 wx.login，页面请求等待同一认证 Promise。",
      "服务端以微信 code 调用 jscode2session，不接受客户端直接提交 openid、unionid 或 userId。",
      "code、openid、unionid 和 session_key 不返回客户端，不写业务日志。"
    ],
    idempotent: true,
  }),
  endpoint({
    id: "runtime_config_get",
    module: "system",
    name: "获取当前用户运行时配置",
    method: "GET",
    path: "/runtime-config",
    usedBy: ["app.js"],
    response: { $ref: "RuntimeConfig" },
    rules: ["平台策略或用户覆盖变化后通过 policyVersion 使客户端缓存失效。", "未开启能力不返回名称和说明。"],
  }),
  endpoint({
    id: "profile_get",
    module: "profile",
    name: "获取个人资料",
    method: "GET",
    path: "/profile",
    usedBy: pages.profile,
    response: { $ref: "Profile" },
  }),
  endpoint({
    id: "profile_update",
    module: "profile",
    name: "更新头像昵称",
    method: "PUT",
    path: "/profile",
    usedBy: pages.profile,
    request: { body: { nickname: "string|required|max:30", avatarFileId: "string|optional" } },
    response: { $ref: "Profile" },
    rules: ["昵称使用微信 nickname 输入能力或手工输入；头像先经过图片上传接口。"],
    idempotent: true,
  }),
  endpoint({
    id: "metadata_get",
    module: "system",
    name: "获取分类、标签、单位与运行时配置",
    method: "GET",
    path: "/metadata",
    usedBy: [...pages.dishForm, ...pages.recommend, ...pages.whatToEat],
    response: {
      dishCategories: "DishCategory[]",
      dishTags: "DishTag[]",
      ingredientUnits: "string[]",
      runtimeConfig: { $ref: "RuntimeConfig" },
    },
    rules: ["V1 分类和标签由平台配置，用户不能自定义分类。"],
  }),
  endpoint({
    id: "image_upload",
    module: "upload",
    name: "上传业务图片并同步内容审核",
    method: "POST",
    path: "/uploads/images",
    usedBy: [...pages.dishForm, ...pages.checkin],
    request: { multipart: { file: "binary|required", scene: "profile_avatar|dish_cover|dish_step|dish_extract|checkin|required" } },
    response: { fileId: "string", url: "string", width: "number", height: "number", reviewStatus: "passed|rejected", rejectReason: "string|null" },
    rules: ["上传阶段同步审核；审核失败当场返回，不进入通知中心。", "客户端压缩后上传，服务端仍需校验 MIME、大小与图片内容。"],
    idempotent: true,
  }),

  endpoint({
    id: "dish_list",
    module: "dish",
    name: "分页查询个人菜品",
    method: "GET",
    path: "/dishes",
    usedBy: [...pages.home, ...pages.dishForm, ...pages.recipes, ...pages.meal, ...pages.profile],
    request: { query: { page: "number|default:1", pageSize: "number|default:20|max:100", q: "string|optional", category: "string|optional", status: "draft|usable|optional" } },
    response: { $ref: "Page<DishSummary>" },
    pagination: true,
    rules: ["只返回当前用户有权查看的个人菜品。", "列表按 updatedAt 倒序。"],
  }),
  endpoint({
    id: "dish_detail",
    module: "dish",
    name: "获取个人菜品详情",
    method: "GET",
    path: "/dishes/{dishId}",
    usedBy: [...pages.dishDetail, ...pages.dishForm],
    request: { path: { dishId: "string|required" } },
    response: { $ref: "Dish" },
  }),
  endpoint({
    id: "dish_create",
    module: "dish",
    name: "创建个人菜品",
    method: "POST",
    path: "/dishes",
    usedBy: ["pages/dish/add-entry"],
    request: { body: { $ref: "DishUpsertInput" } },
    response: { $ref: "Dish" },
    rules: ["封面图必填；简介选填；标签最多 3 个。", "可保存为 draft 或 usable。"],
    idempotent: true,
  }),
  endpoint({
    id: "dish_update",
    module: "dish",
    name: "编辑个人菜品",
    method: "PUT",
    path: "/dishes/{dishId}",
    usedBy: ["pages/dish/edit"],
    request: { path: { dishId: "string|required" }, body: { $ref: "DishUpsertInput" } },
    response: { $ref: "Dish" },
    rules: ["从平台推荐或增强建议保存的菜品可编辑内容，但 sourceLocked 永久为 true。"],
    idempotent: true,
  }),
  endpoint({
    id: "dish_delete",
    module: "dish",
    name: "删除个人菜品",
    method: "DELETE",
    path: "/dishes/{dishId}",
    usedBy: pages.dishDetail,
    request: { path: { dishId: "string|required" } },
    response: { deleted: "boolean", affectedRecipeCount: "number", affectedMealCount: "number" },
    rules: ["删除菜品时从菜谱和未关闭饭局候选中移除引用。"],
    idempotent: true,
  }),
  endpoint({
    id: "dish_discoverable_update",
    module: "dish",
    name: "设置允许被发现",
    method: "PUT",
    path: "/dishes/{dishId}/discoverable",
    usedBy: pages.dishDetail,
    request: { path: { dishId: "string|required" }, body: { discoverable: "boolean|required" } },
    response: { $ref: "Dish" },
    rules: ["界面口径为“允许被发现/未公开”，不使用“公开状态”或单独审核。", "sourceLocked=true 的菜品不能设置为允许被发现。", "管理员加入推荐即完成挑选行为，不设置独立审核状态。"],
    idempotent: true,
  }),
  endpoint({
    id: "dish_extract",
    module: "assist",
    name: "整理菜品资料并返回可编辑字段",
    method: "POST",
    path: "/assist/dish-extraction",
    usedBy: ["pages/dish/add-entry"],
    request: { body: { text: "string|optional", imageFileId: "string|optional" } },
    response: { dishDraft: { $ref: "DishUpsertInput" }, usage: { $ref: "FeatureUsageResult" } },
    rules: ["能力编码为 dish_extract。", "text 与 imageFileId 至少提供一个。", "结果仅填充表单，用户确认保存后才创建菜品。", "处理失败或超时产生独立积分退还流水。"],
    idempotent: true,
  }),
  endpoint({
    id: "dish_cover_create",
    module: "assist",
    name: "创建菜品封面",
    method: "POST",
    path: "/assist/dish-covers",
    usedBy: pages.dishForm,
    request: { body: { name: "string|required", description: "string|optional", category: "string|optional" } },
    response: { fileId: "string", url: "string", usage: { $ref: "FeatureUsageResult" } },
    rules: ["能力编码为 cover_create。", "生成图应表现真实菜品，不使用简陋矢量占位图。"],
    idempotent: true,
  }),

  endpoint({
    id: "recommendation_list",
    module: "recommendation",
    name: "分页查询菜品推荐",
    method: "GET",
    path: "/recommendations",
    usedBy: [...pages.home, "pages/recommend/dishes"],
    request: { query: { page: "number|default:1", pageSize: "number|default:20", category: "string|optional", tags: "string[]|optional" } },
    response: { $ref: "Page<RecommendationSummary>" },
    pagination: true,
    rules: ["推荐来源必须区分 official 与 creator。", "仅返回管理员当前挑选进入推荐的菜品。"],
  }),
  endpoint({
    id: "recommendation_detail",
    module: "recommendation",
    name: "获取推荐菜品详情",
    method: "GET",
    path: "/recommendations/{recommendationId}",
    usedBy: ["pages/recommend/dish-detail"],
    request: { path: { recommendationId: "string|required" } },
    response: { $ref: "Recommendation" },
    rules: ["详情只读并展示作者；平台发布时展示官方身份。"],
  }),
  endpoint({
    id: "recommendation_copy",
    module: "recommendation",
    name: "复制推荐菜品到个人菜品库",
    method: "POST",
    path: "/recommendations/{recommendationId}/copy",
    usedBy: [...pages.home, "pages/recommend/dish-detail"],
    request: { path: { recommendationId: "string|required" } },
    response: { dish: { $ref: "Dish" }, alreadyCopied: "boolean" },
    rules: ["复制后可编辑、默认未公开、sourceLocked=true，永久不能再次允许被发现。", "重复请求返回已有复制结果。"],
    idempotent: true,
  }),

  endpoint({
    id: "meal_suggestion_status",
    module: "assist",
    name: "获取不知道吃什么可用状态",
    method: "GET",
    path: "/meal-suggestions/status",
    usedBy: ["pages/ideas/what-to-eat"],
    response: { enabled: "boolean", unlocked: "boolean", checkinDays: "number", unlockDays: "number", freeQuota: "number", pointBalance: "number|null", pointCost: "number|null" },
    rules: ["能力编码为 meal_suggest。", "累计做菜打卡满 7 天后解锁。", "当前用户能力关闭时接口返回 46001。"],
  }),
  endpoint({
    id: "meal_suggestion_create",
    module: "assist",
    name: "生成个性化菜品推荐",
    method: "POST",
    path: "/meal-suggestions",
    usedBy: ["pages/ideas/what-to-eat"],
    request: { body: { tags: "string[]", people: "number|required|min:1|max:20", timeLimitMinutes: "number|optional", excludedRecommendationIds: "string[]|optional", useFreeQuota: "boolean" } },
    response: { $ref: "MealSuggestion" },
    rules: ["能力编码为 meal_suggest。", "先用 SQL 按硬条件查询推荐库，不使用外部模型做数据库筛选。", "推荐库样本不足时才调用外部模型补充。", "补充结果只能是现实存在的经典菜系、常见材料和可验证做法，不得虚构。", "仅保存到菜品库时记为采用。", "一人返回精简方案，两人及多人按人数返回多道菜组合，并兼顾荤素、汤菜和总菜量。"],
    idempotent: true,
  }),
  endpoint({
    id: "meal_suggestion_detail",
    module: "assist",
    name: "获取菜品建议详情",
    method: "GET",
    path: "/meal-suggestions/{suggestionId}",
    usedBy: ["pages/ideas/what-to-eat-detail"],
    request: { path: { suggestionId: "string|required" } },
    response: { $ref: "MealSuggestion" },
  }),
  endpoint({
    id: "meal_suggestion_copy",
    module: "assist",
    name: "保存菜品建议到个人菜品库",
    method: "POST",
    path: "/meal-suggestions/{suggestionId}/copy",
    usedBy: ["pages/ideas/what-to-eat-detail"],
    request: { path: { suggestionId: "string|required" } },
    response: { dish: { $ref: "Dish" }, adoptionRecorded: "boolean" },
    rules: ["保存后生成未公开、sourceLocked=true 的个人菜品。", "此接口成功才记录推荐采用。"],
    idempotent: true,
  }),
  endpoint({
    id: "meal_suggestion_feedback",
    module: "assist",
    name: "记录忽略或换一道反馈",
    method: "POST",
    path: "/meal-suggestions/{suggestionId}/feedback",
    usedBy: ["pages/ideas/what-to-eat"],
    request: { path: { suggestionId: "string|required" }, body: { action: "ignored|regenerated|required" } },
    response: { recorded: "boolean" },
    idempotent: true,
  }),

  endpoint({
    id: "recipe_list",
    module: "recipe",
    name: "查询个人菜谱",
    method: "GET",
    path: "/recipes",
    usedBy: [...pages.recipes, "pages/meal/create"],
    response: { list: "RecipeSummary[]" },
  }),
  endpoint({
    id: "recipe_create",
    module: "recipe",
    name: "创建菜谱",
    method: "POST",
    path: "/recipes",
    usedBy: ["pages/recipes/index"],
    request: { body: { name: "string|required|max:30", note: "string|optional|max:100", dishIds: "string[]|optional" } },
    response: { $ref: "Recipe" },
    idempotent: true,
  }),
  endpoint({
    id: "recipe_detail",
    module: "recipe",
    name: "获取菜谱详情",
    method: "GET",
    path: "/recipes/{recipeId}",
    usedBy: ["pages/recipes/detail"],
    request: { path: { recipeId: "string|required" } },
    response: { $ref: "Recipe" },
  }),
  endpoint({
    id: "recipe_update",
    module: "recipe",
    name: "更新菜谱名称备注",
    method: "PUT",
    path: "/recipes/{recipeId}",
    usedBy: ["pages/recipes/detail"],
    request: { path: { recipeId: "string|required" }, body: { name: "string|optional|max:30", note: "string|optional|max:100", dishIds: "string[]|optional" } },
    response: { $ref: "Recipe" },
    idempotent: true,
  }),
  endpoint({
    id: "recipe_delete",
    module: "recipe",
    name: "删除菜谱",
    method: "DELETE",
    path: "/recipes/{recipeId}",
    usedBy: ["pages/recipes/detail"],
    request: { path: { recipeId: "string|required" } },
    response: { deleted: "boolean" },
    rules: ["删除菜谱不会删除个人菜品。"],
    idempotent: true,
  }),
  endpoint({
    id: "recipe_dish_add",
    module: "recipe",
    name: "向菜谱添加菜品",
    method: "POST",
    path: "/recipes/{recipeId}/dishes",
    usedBy: ["pages/recipes/detail"],
    request: { path: { recipeId: "string|required" }, body: { dishIds: "string[]|required" } },
    response: { $ref: "Recipe" },
    rules: ["只能选择已编辑好的个人可用菜品。"],
    idempotent: true,
  }),
  endpoint({
    id: "recipe_dish_remove",
    module: "recipe",
    name: "从菜谱移除菜品",
    method: "DELETE",
    path: "/recipes/{recipeId}/dishes/{dishId}",
    usedBy: ["pages/recipes/detail"],
    request: { path: { recipeId: "string|required", dishId: "string|required" } },
    response: { $ref: "Recipe" },
    idempotent: true,
  }),

  endpoint({
    id: "checkin_calendar",
    module: "checkin",
    name: "获取月度打卡日历",
    method: "GET",
    path: "/checkins/calendar",
    usedBy: pages.checkin,
    request: { query: { month: "YYYY-MM|required" } },
    response: { month: "string", checkedDates: "string[]", checkinDays: "number" },
  }),
  endpoint({
    id: "checkin_list",
    module: "checkin",
    name: "分页查询打卡记录",
    method: "GET",
    path: "/checkins",
    usedBy: pages.checkin,
    request: { query: { page: "number|default:1", pageSize: "number|default:20" } },
    response: { $ref: "Page<Checkin>" },
    pagination: true,
  }),
  endpoint({
    id: "checkin_create",
    module: "checkin",
    name: "新增做菜打卡",
    method: "POST",
    path: "/checkins",
    usedBy: pages.checkin,
    request: { body: { dishId: "string|required", imageFileId: "string|required", note: "string|optional|max:120" } },
    response: { checkin: { $ref: "Checkin" }, rewardGranted: "boolean", rewardAmount: "number", preferenceUpdateQueued: "boolean" },
    rules: ["当前用户增强能力开启时，每日仅首次打卡获得积分。", "当前用户增强能力关闭时仍保存打卡，但 rewardGranted=false、rewardAmount=0，不写奖励流水且不投递偏好更新任务。", "能力开启时，打卡后异步分析图片并更新用户菜品喜好画像；分析失败不影响打卡成功。"],
    idempotent: true,
  }),

  endpoint({
    id: "meal_list",
    module: "meal",
    name: "分页查询饭局",
    method: "GET",
    path: "/meals",
    usedBy: pages.profile,
    request: { query: { page: "number|default:1", pageSize: "number|default:20", scope: "active|history" } },
    response: { $ref: "Page<MealSummary>" },
    pagination: true,
  }),
  endpoint({
    id: "meal_current",
    module: "meal",
    name: "获取当前进行中饭局",
    method: "GET",
    path: "/meals/current",
    usedBy: [...pages.home, ...pages.profile, ...pages.meal],
    response: { meal: "Meal|null" },
  }),
  endpoint({
    id: "meal_create",
    module: "meal",
    name: "创建饭局并生成点餐码",
    method: "POST",
    path: "/meals",
    usedBy: ["pages/meal/create"],
    request: { body: { name: "string|required|max:30", deadlineAt: "datetime|required", candidateDishIds: "string[]|required|min:1", sourceRecipeId: "string|optional" } },
    response: { $ref: "Meal" },
    idempotent: true,
  }),
  endpoint({
    id: "meal_detail",
    module: "meal",
    name: "获取饭局详情",
    method: "GET",
    path: "/meals/{mealId}",
    usedBy: pages.meal,
    request: { path: { mealId: "string|required" } },
    response: { $ref: "Meal" },
  }),
  endpoint({
    id: "meal_lookup",
    module: "meal",
    name: "通过点餐码预览饭局",
    method: "POST",
    path: "/meals/lookup",
    usedBy: ["pages/meal/vote"],
    request: { body: { code: "string|required|length:6" } },
    response: { $ref: "MealJoinPreview" },
    rules: ["仅返回加入确认所需摘要，不产生加入行为。", "无效、关闭、到期或取消的饭局返回不可加入状态。"],
    idempotent: true,
  }),
  endpoint({
    id: "meal_join",
    module: "meal",
    name: "通过点餐码加入饭局",
    method: "POST",
    path: "/meals/join",
    usedBy: ["pages/meal/vote"],
    request: { body: { code: "string|required|length:6" } },
    response: { $ref: "Meal" },
    rules: ["关闭、到期或取消的饭局不能加入。"],
    idempotent: true,
  }),
  endpoint({
    id: "meal_close",
    module: "meal",
    name: "提前关闭点餐",
    method: "POST",
    path: "/meals/{mealId}/close",
    usedBy: ["pages/meal/invite"],
    request: { path: { mealId: "string|required" } },
    response: { $ref: "Meal" },
    rules: ["仅发起人可操作；关闭后不能再修改点菜。"],
    idempotent: true,
  }),
  endpoint({
    id: "meal_cancel",
    module: "meal",
    name: "取消饭局",
    method: "POST",
    path: "/meals/{mealId}/cancel",
    usedBy: ["pages/meal/invite"],
    request: { path: { mealId: "string|required" }, body: { reason: "string|optional|max:100" } },
    response: { $ref: "Meal" },
    idempotent: true,
  }),
  endpoint({
    id: "meal_candidate_list",
    module: "meal",
    name: "按分类查询饭局候选菜",
    method: "GET",
    path: "/meals/{mealId}/candidates",
    usedBy: ["pages/meal/vote"],
    request: { path: { mealId: "string|required" }, query: { category: "string|optional" } },
    response: { categories: "CategoryCount[]", list: "MealCandidate[]" },
    rules: ["候选菜可按分类切换；V1 候选数量有限，不需要接口分页。"],
  }),
  endpoint({
    id: "meal_vote_get",
    module: "meal",
    name: "获取我的点菜",
    method: "GET",
    path: "/meals/{mealId}/votes/me",
    usedBy: ["pages/meal/vote"],
    request: { path: { mealId: "string|required" } },
    response: { dishIds: "string[]", updatedAt: "datetime|null" },
  }),
  endpoint({
    id: "meal_vote_update",
    module: "meal",
    name: "保存我的点菜",
    method: "PUT",
    path: "/meals/{mealId}/votes/me",
    usedBy: ["pages/meal/vote"],
    request: { path: { mealId: "string|required" }, body: { dishIds: "string[]|required" } },
    response: { dishIds: "string[]", savedAt: "datetime" },
    rules: ["允许多选；饭局关闭前可覆盖修改。"],
    idempotent: true,
  }),
  endpoint({
    id: "meal_stats",
    module: "meal",
    name: "获取点菜统计与建议份量",
    method: "GET",
    path: "/meals/{mealId}/stats",
    usedBy: ["pages/meal/stats"],
    request: { path: { mealId: "string|required" } },
    response: { meal: { $ref: "MealSummary" }, dishes: "MealDishStat[]" },
  }),
  endpoint({
    id: "meal_confirm",
    module: "meal",
    name: "确认最终菜单并生成采购清单",
    method: "POST",
    path: "/meals/{mealId}/confirm",
    usedBy: ["pages/meal/stats"],
    request: { path: { mealId: "string|required" }, body: { dishes: "FinalMenuDish[]|required|min:1" } },
    response: { meal: { $ref: "Meal" }, shoppingListId: "string" },
    rules: ["仅发起人可确认；按最终份数合并同名、同单位食材。"],
    idempotent: true,
  }),

  endpoint({
    id: "shopping_list_get",
    module: "shopping",
    name: "获取当前采购清单",
    method: "GET",
    path: "/shopping-lists/current",
    usedBy: pages.shopping,
    response: { $ref: "ShoppingList" },
    rules: ["采购项不做分类，按 sortOrder 顺序展示。"],
  }),
  endpoint({
    id: "shopping_list_shared_get",
    module: "shopping",
    name: "通过分享标识获取只读采购清单",
    method: "GET",
    path: "/shopping-lists/shared/{shareToken}",
    usedBy: pages.shoppingShare,
    request: { path: { shareToken: "string|required" } },
    response: { $ref: "SharedShoppingList" },
    rules: [
      "分享标识必须不可枚举，不直接暴露采购清单 ID。",
      "该接口只返回只读数据；非创建者不能通过分享标识调用新增、编辑、删除或勾选接口。",
      "分享页展示当前清单的最新状态。",
    ],
  }),
  endpoint({
    id: "shopping_item_create",
    module: "shopping",
    name: "新增采购项",
    method: "POST",
    path: "/shopping-lists/current/items",
    usedBy: pages.shopping,
    request: { body: { name: "string|required|max:40", amount: "string|required|max:30", note: "string|optional|max:100" } },
    response: { $ref: "ShoppingItem" },
    idempotent: true,
  }),
  endpoint({
    id: "shopping_item_update",
    module: "shopping",
    name: "编辑采购项",
    method: "PUT",
    path: "/shopping-lists/current/items/{itemId}",
    usedBy: pages.shopping,
    request: { path: { itemId: "string|required" }, body: { name: "string|optional|max:40", amount: "string|optional|max:30", note: "string|optional|max:100", completed: "boolean|optional", sortOrder: "number|optional" } },
    response: { $ref: "ShoppingItem" },
    idempotent: true,
  }),
  endpoint({
    id: "shopping_item_delete",
    module: "shopping",
    name: "删除采购项",
    method: "DELETE",
    path: "/shopping-lists/current/items/{itemId}",
    usedBy: pages.shopping,
    request: { path: { itemId: "string|required" } },
    response: { deleted: "boolean" },
    idempotent: true,
  }),
  endpoint({
    id: "shopping_export_text",
    module: "shopping",
    name: "获取可复制分享的采购清单文本",
    method: "GET",
    path: "/shopping-lists/{listId}/export-text",
    usedBy: pages.shopping,
    request: { path: { listId: "string|required" } },
    response: { title: "string", text: "string", updatedAt: "datetime" },
    rules: ["复制文本使用导出接口；微信分享路径指向 pages/shopping/share 并携带不可枚举的 shareToken。"],
  }),

  endpoint({
    id: "prep_plan_quote",
    module: "assist",
    name: "获取备菜顺序生成费用",
    method: "GET",
    path: "/prep-plans/quote",
    usedBy: pages.prep,
    request: { query: { mealId: "string|required" } },
    response: { pointCost: "number", pointBalance: "number", canGenerate: "boolean" },
    rules: ["能力编码为 prep_sequence。", "当前用户能力关闭时接口返回 46001。"],
  }),
  endpoint({
    id: "prep_plan_generate",
    module: "assist",
    name: "生成跨菜品备菜顺序",
    method: "POST",
    path: "/prep-plans",
    usedBy: pages.prep,
    request: { body: { mealId: "string|required", excludedPlanIds: "string[]|optional" } },
    response: { $ref: "PrepPlan" },
    rules: ["能力编码为 prep_sequence。", "输出细化到操作顺序，并包含“等待时同时做”和“完成标志”。", "文案避免使用“启动”等生硬描述。", "失败或超时产生独立积分退还流水。"],
    idempotent: true,
  }),
  endpoint({
    id: "prep_plan_detail",
    module: "assist",
    name: "获取备菜顺序详情",
    method: "GET",
    path: "/prep-plans/{planId}",
    usedBy: pages.prep,
    request: { path: { planId: "string|required" } },
    response: { $ref: "PrepPlan" },
  }),
  endpoint({
    id: "prep_plan_feedback",
    module: "assist",
    name: "记录忽略或重新生成备菜顺序",
    method: "POST",
    path: "/prep-plans/{planId}/feedback",
    usedBy: pages.prep,
    request: { path: { planId: "string|required" }, body: { action: "ignored|regenerated|required" } },
    response: { recorded: "boolean" },
    idempotent: true,
  }),

  endpoint({
    id: "points_summary",
    module: "points",
    name: "获取积分汇总",
    method: "GET",
    path: "/points/summary",
    usedBy: [...pages.profile, ...pages.points],
    response: { balance: "number", monthEarned: "number", monthSpent: "number" },
    rules: ["汇总与流水分开查询。", "不提供充值、支付或购买积分入口。", "当前用户增强能力关闭时接口返回 46002。"],
  }),
  endpoint({
    id: "points_entries",
    module: "points",
    name: "分页查询积分流水",
    method: "GET",
    path: "/points/entries",
    usedBy: pages.points,
    request: { query: { page: "number|default:1", pageSize: "number|default:20", type: "all|earned|spent|refund|default:all" } },
    response: { $ref: "Page<PointEntry>" },
    pagination: true,
    rules: ["按 createdAt、id 倒序稳定分页。", "小程序隐藏页码，接近底部自动加载并按流水 ID 去重。", "失败退还是独立流水，并关联原能力消耗记录。", "当前用户增强能力关闭时接口返回 46002。"],
  }),
  endpoint({
    id: "feature_usage_list",
    module: "points",
    name: "分页查询增强能力使用记录",
    method: "GET",
    path: "/feature-usages",
    usedBy: pages.profile,
    request: { query: { page: "number|default:1", pageSize: "number|default:20", feature: "string|optional", status: "success|failed|refunded|optional" } },
    response: { $ref: "Page<FeatureUsage>" },
    pagination: true,
    rules: ["当前用户增强能力关闭时接口返回 46001。"],
  }),

  endpoint({
    id: "notifications_summary",
    module: "notification",
    name: "获取通知汇总",
    method: "GET",
    path: "/notifications/summary",
    usedBy: [...pages.profile, ...pages.notifications],
    response: { unreadCount: "number", total: "number" },
  }),
  endpoint({
    id: "notifications_list",
    module: "notification",
    name: "分页查询通知",
    method: "GET",
    path: "/notifications",
    usedBy: pages.notifications,
    request: { query: { page: "number|default:1", pageSize: "number|default:20", scope: "unread|all|default:unread" } },
    response: { $ref: "Page<Notification>" },
    pagination: true,
    rules: ["默认查询未读，界面左侧为未读、右侧为全部。", "按 createdAt、id 倒序稳定分页，界面无限滚动且不展示页码。", "内容治理、允许被发现变化、积分、处理失败退还和饭局状态分别使用明确文案。"],
  }),
  endpoint({
    id: "notification_read",
    module: "notification",
    name: "标记单条通知已读",
    method: "POST",
    path: "/notifications/{notificationId}/read",
    usedBy: pages.notifications,
    request: { path: { notificationId: "string|required" } },
    response: { read: "boolean", readAt: "datetime" },
    idempotent: true,
  }),
  endpoint({
    id: "notifications_read_all",
    module: "notification",
    name: "全部标为已读",
    method: "POST",
    path: "/notifications/read-all",
    usedBy: pages.notifications,
    response: { affected: "number", unreadCount: "number" },
    rules: ["只更新阅读状态，不删除历史通知。"],
    idempotent: true,
  }),
];

const document = {
  name: "来干饭微信小程序 API 接口清单",
  version: "1.2.0",
  generatedAt: "2026-07-24",
  source: [
    "aiDoc/prd/family-menu-miniapp-prd.md",
    "aiDoc/prd/family-menu-miniapp-feature-mindmap.md",
    "aiDoc/prd/dish-and-recipe-creation-flowchart.md",
    "aiDoc/prd/meal-order-to-purchase-flowchart.md",
    "aiDoc/frontend-backend/order-food-contract-baseline.md",
    "aiDoc/frontend-backend/miniapp-auth-capability-compliance.md",
    "aiDoc/miniApp/task.json"
  ],
  basePath: "/api/miniapp/v1",
  transport: {
    protocol: "HTTPS",
    contentType: "application/json",
    authorization: "Bearer <accessToken>",
    traceHeader: "X-Request-Id",
    mutationIdempotencyHeader: "X-Idempotency-Key"
  },
  responseEnvelope: {
    success: { code: 0, data: "object|array|null", msg: "ok" },
    error: { code: "non-zero integer", data: null, msg: "human-readable message" }
  },
  pagination: {
    request: { page: "number, starts at 1", pageSize: "number, default 20" },
    response: { page: "number", pageSize: "number", total: "number", list: "array" },
    clientBehavior: "界面不展示页码；接近底部加载下一页；切换筛选和下拉刷新时重置为第 1 页；追加时按 id 去重。"
  },
  commonErrorCodes: {
    "40001": "请求参数错误",
    "40101": "登录已过期",
    "40102": "微信登录凭证无效、已使用或兑换失败",
    "40301": "无权操作该资源",
    "40401": "资源不存在",
    "40901": "状态冲突或重复操作",
    "42201": "图片内容审核不通过",
    "42901": "请求过于频繁",
    "46001": "当前功能未开放",
    "46002": "积分功能未开放",
    "47001": "积分不足",
    "47002": "当前功能未解锁",
    "47003": "处理失败，积分已退还"
  },
  enums: {
    DishStatus: ["draft", "usable"],
    RecommendationSourceType: ["official", "creator"],
    MealStatus: ["collecting", "closed", "confirmed", "cancelled"],
    MealCloseReason: ["manual", "deadline"],
    CapabilityOverride: ["inherit", "enabled", "disabled"],
    PointEntryType: ["earned", "spent", "refund", "adjustment"],
    NotificationType: ["governance", "discoverability", "points", "feature_refund", "meal"]
  },
  models: {
    Profile: {
      id: "string",
      nickname: "string",
      avatarUrl: "string|null",
      points: "number|null",
      checkinDays: "number"
    },
    ClientFeature: {
      code: "dish_extract|cover_create|meal_suggest|prep_sequence|taste_profile",
      title: "string",
      actionText: "string",
      description: "string",
      enabled: "true",
      pointCost: "number|null",
      freeQuota: "number|null",
      sortOrder: "number"
    },
    RuntimeConfig: {
      policyVersion: "number",
      enhancedFeaturesEnabled: "boolean",
      pointsEnabled: "boolean",
      features: "ClientFeature[]"
    },
    Ingredient: { id: "string", name: "string", amount: "string", unit: "string", note: "string|null", sortOrder: "number" },
    IngredientInput: {
      name: "string|required|max:30",
      amount: "string|required|max:20",
      unit: "string|required|max:10",
      note: "string|optional|max:80",
      sortOrder: "number|required|min:1"
    },
    DishStep: { id: "string", text: "string", imageUrl: "string|null", sortOrder: "number" },
    DishStepInput: {
      text: "string|required|max:500",
      imageFileId: "string|null",
      sortOrder: "number|required|min:1"
    },
    DishCategory: { id: "string", name: "string", sortOrder: "number", enabled: "boolean" },
    DishTag: { id: "string", name: "string", sortOrder: "number", enabled: "boolean" },
    AuthorSummary: { id: "string|null", name: "string", avatarUrl: "string|null", type: "official|creator" },
    DishSummary: {
      id: "string",
      name: "string",
      category: "string",
      tags: "string[]",
      coverUrl: "string",
      serving: "number",
      status: "DishStatus",
      discoverable: "boolean",
      sourceLocked: "boolean"
    },
    Dish: {
      allOf: ["DishSummary"],
      description: "string|null",
      ingredients: "Ingredient[]",
      steps: "DishStep[]",
      createdAt: "datetime",
      updatedAt: "datetime"
    },
    DishUpsertInput: {
      name: "string|required|max:40",
      category: "string|required",
      tags: "string[]|maxItems:3",
      serving: "number|required|min:1|max:20",
      description: "string|optional|max:180",
      coverFileId: "string|required",
      status: "draft|usable|required",
      ingredients: "IngredientInput[]",
      steps: "DishStepInput[]"
    },
    RecommendationSummary: {
      allOf: ["DishSummary"],
      recommendationId: "string",
      sourceType: "official|creator",
      author: "AuthorSummary",
      copied: "boolean"
    },
    Recommendation: {
      allOf: ["RecommendationSummary"],
      description: "string",
      ingredients: "Ingredient[]",
      steps: "DishStep[]"
    },
    RecipeSummary: { id: "string", name: "string", note: "string|null", dishCount: "number", coverUrl: "string|null" },
    Recipe: { allOf: ["RecipeSummary"], dishIds: "string[]", dishes: "DishSummary[]", updatedAt: "datetime" },
    Checkin: { id: "string", dishId: "string", dishName: "string", imageUrl: "string", note: "string|null", checkedAt: "datetime", rewarded: "boolean" },
    MealSummary: { id: "string", name: "string", code: "string", status: "MealStatus", closeReason: "MealCloseReason|null", deadlineAt: "datetime", participantCount: "number", candidateCount: "number" },
    MealJoinPreview: { id: "string", name: "string", status: "MealStatus", deadlineAt: "datetime", participantCount: "number", candidateCount: "number" },
    MealCandidate: {
      id: "string",
      dishId: "string",
      name: "string",
      coverUrl: "string",
      category: "string",
      tags: "string[]",
      voteCount: "number",
      selectedByMe: "boolean",
      available: "boolean",
      sortOrder: "number"
    },
    MealDishStat: {
      candidateId: "string",
      dishId: "string",
      name: "string",
      coverUrl: "string",
      category: "string",
      tags: "string[]",
      voteCount: "number",
      baseServing: "number",
      suggestedServings: "number",
      selected: "boolean",
      finalServings: "number"
    },
    FinalMenuDish: {
      candidateId: "string|required",
      selected: "boolean|required",
      finalServings: "number|required|min:0|max:20"
    },
    CategoryCount: { category: "string", count: "number" },
    Meal: { allOf: ["MealSummary"], candidateDishIds: "string[]", candidates: "MealCandidate[]", createdByMe: "boolean" },
    ShoppingItem: { id: "string", name: "string", amount: "string", note: "string|null", completed: "boolean", sortOrder: "number" },
    ShoppingList: { id: "string", shareToken: "string", meal: "MealSummary", items: "ShoppingItem[]", pendingCount: "number", completedCount: "number" },
    SharedShoppingList: { id: "string", meal: "MealSummary", items: "ShoppingItem[]", pendingCount: "number", completedCount: "number", readOnly: "true" },
    FeatureUsageResult: { usageId: "string", pointCost: "number", refunded: "boolean", pointBalance: "number" },
    MealSuggestion: { id: "string", source: "library|generated", sourceLabel: "string", reason: "string", people: "number", suggestedDishCount: "number", dish: "Recommendation", dishes: "Recommendation[]", usage: "FeatureUsageResult" },
    PrepStep: {
      id: "string",
      order: "number",
      title: "string",
      instruction: "string",
      parallelActions: "string[]",
      waitMinutes: "number|null",
      completionHint: "string"
    },
    PrepPlan: { id: "string", mealId: "string", estimatedMinutes: "number", steps: "PrepStep[]", usage: "FeatureUsageResult" },
    PointEntry: { id: "string", type: "PointEntryType", title: "string", description: "string", amount: "number", relatedEntryId: "string|null", createdAt: "datetime" },
    FeatureUsage: { id: "string", feature: "string", pointCost: "number", status: "success|failed|refunded", createdAt: "datetime" },
    Notification: { id: "string", type: "NotificationType", title: "string", content: "string", targetType: "string|null", targetId: "string|null", read: "boolean", createdAt: "datetime" },
    BootstrapData: { profile: "Profile", runtimeConfig: "RuntimeConfig", dishes: "DishSummary[0..3]", recommendations: "RecommendationSummary[0..5]", activeMeal: "MealSummary|null", unreadCount: "number" }
  },
  interfaces
};

const output = path.resolve(__dirname, "..", "api.json");
fs.writeFileSync(output, `${JSON.stringify(document, null, 2)}\n`, "utf8");
console.log(JSON.stringify({ output, interfaceCount: interfaces.length, moduleCount: new Set(interfaces.map((item) => item.module)).size }));
